package org.redvelvet.example.web.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.organize_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    private Integer organizeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.organize_id
     *
     * @return the value of user.organize_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public Integer getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.organize_id
     *
     * @param organizeId the value for user.organize_id
     *
     * @mbggenerated Wed Mar 30 21:33:00 CST 2016
     */
    public void setOrganizeId(Integer organizeId) {
        this.organizeId = organizeId;
    }
}